### ISSUE TITLE
Can't run demo("BC")

### ISSUE THREAD

**Issue by HeikeSp** [rwehrens/BatchCorrMetabolomics#1]
Dear Ron,
when I tried to run the demo of your package I got the following error messages.

``` R
> library(BatchCorrMetabolomics)
> demo("doBC")
Error in demo("doBC") : No demo found for topic ‘doBC’
> demo("BC")
Error in demo("BC") : No demo found for topic ‘BC’
> demo("BC", package = "BatchCorrMetabolomics")
Error in demo("BC", package = "BatchCorrMetabolomics") : 
  No demo found for topic ‘BC’
```

It seems that the file `BC.R` contains only an absolute path to one of your local files.

Best wishes,
Heike

**Comment by rwehrens** [comment]
On 04/05/2016 11:50 PM, HeikeSp wrote:

> Dear Ron,
> when I tried to run the demo of your package I got the following error
> messages.
> 
> >  library(BatchCorrMetabolomics)
> >  demo("doBC")
> > Error  in  demo("doBC"):  No  demo  found  for  topic  ‘doBC’
> >  demo("BC")
> > Error  in  demo("BC"):  No  demo  found  for  topic  ‘BC’
> >  demo("BC",package  =  "BatchCorrMetabolomics")
> > Error  in  demo("BC",package  =  "BatchCorrMetabolomics"):
> >    No  demo  found  for  topic  ‘BC’
> 
> It seems that the file |BC.R| contains only an absolute path to one of
> your local files.
> 
> Best wishes,
> Heike
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/rwehrens/BatchCorrMetabolomics/issues/1

Have you tried

demo(BC)

without the quotes? That works for me...

Cheers,
R

**Comment by rwehrens** [comment]
On 04/05/2016 11:50 PM, HeikeSp wrote:

> Dear Ron,
> when I tried to run the demo of your package I got the following error
> messages.
> 
> >  library(BatchCorrMetabolomics)
> >  demo("doBC")
> > Error  in  demo("doBC"):  No  demo  found  for  topic  ‘doBC’
> >  demo("BC")
> > Error  in  demo("BC"):  No  demo  found  for  topic  ‘BC’
> >  demo("BC",package  =  "BatchCorrMetabolomics")
> > Error  in  demo("BC",package  =  "BatchCorrMetabolomics"):
> >    No  demo  found  for  topic  ‘BC’
> 
> It seems that the file |BC.R| contains only an absolute path to one of
> your local files.
> 
> Best wishes,
> Heike
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/rwehrens/BatchCorrMetabolomics/issues/1

Sorry about my previous response - the quotes do not matter, and was 
misunderstanding your remark about local files.

I repaired the stuff on github, could you please test and let me know if 
it works for you now?

Thanks for letting me know!

Cheers,
Ron

**Comment by HeikeSp** [comment]
Now I can run part of the demo, but at line 312 to 318 I get the following error:

`Error in svd(X) : infinite or missing values in 'x'
In addition: Warning message:
In rlm.default(x, y, weights, method = method, wt.method = wt.method,  :
  'rlm' failed to converge in 50 steps`

**Comment by rwehrens** [comment]
On 04/06/2016 11:33 PM, HeikeSp wrote:

> Now I can run part of the demo, but at line 312 to 318 I get the
> following error:
> 
> |Error in svd(X) : infinite or missing values in 'x'
> In addition: Warning message:
> In rlm.default(x, y, weights, method = method, wt.method = wt.method, :
> 'rlm' failed to converge in 50 steps|
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/rwehrens/BatchCorrMetabolomics/issues/1#issuecomment-206580567

Hi Heike,

thanks again for your feedback. The demo script had a bug, taking logs 
of values that were already on the log scale. This led to many NAs which 
again prompted the svd error you mentioned. This bug was only present in 
the BC.R file - for the paper I used precalculated results. On my 
computer the results are now exactly equal to the ones in the paper, 
please let me know if you find any other difficulties.

Cheers,
Ron

**Comment by HeikeSp** [comment]
Dear Ron,
everything runs smoothly now.

Best wishes,
Heike

**Comment by rwehrens** [comment]
On 04/07/2016 05:19 PM, HeikeSp wrote:

> Dear Ron,
> everything runs smoothly now.
> 
> Best wishes,
> Heike
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/rwehrens/BatchCorrMetabolomics/issues/1#issuecomment-206950159

Great, thanks again for your feedback.

Cheers,
R
